version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build and test
          command: dotnet test --logger "trx;LogFileName=testresults.trx"
